### ISSUE TITLE
[Bug] Mobile responsibility UI issue on `default-page.html`

### ISSUE THREAD

**Issue by SisiVero** [creativecommons/vocabulary#68]
## Description
The interface for the default-page.html needs some adjustments for it to aesthetically pleasing.
At the moment, there is no padding and there is an x overflow for mobile screens.

There should be no x overflow. All contents should fit into the screen vw, this puts UX into consideration.

<img width="146" alt="vocabMobileUI" src="https://github.com/user-attachments/assets/5d7fae49-69cb-4b46-9ac8-f0a41b69f9a5">

## Environment
< - Device: (All mobile screens )

- [x] I would be interested in resolving this bug.

**Comment by possumbilities** [comment]
@SisiVero can you please provide more information like browser, operating system, etc. here around this issue? things like at what specific pixel width is this occurring, more details are needed here.

**Comment by OmarAmeen01** [comment]
Responsiveness Below 400px:

Pages are not responsive on screens smaller than 400px, leading to layout issues and poor user experience on mobile devices.
Lack of Padding on Smaller Screens:

Insufficient padding on smaller screens causes the content to appear cramped, with text and other elements sticking to the edges of the screen.
Text Size on Small Devices:

The text does not scale down appropriately for smaller screens, resulting in oversized text that disrupts the layout and readability.
Post Alignment and Text Size Below 500px:

blog Posts align to the left side of the screen below 500px, and the text appears disproportionately large, making the content difficult to read. it causes shrinking of nav and footer that is they become lesser than window width

I can fix this assign it to me or let me know if I can take it

**Comment by SisiVero** [comment]
Hi @possumbilities . The browser in use is the Chrome browser.
The issues occurred  from 540 to 320 pixels, as I've confirmed.

**Comment by iyinolawumi** [comment]
Hi @possumbilities . The responsiveness for the default .html is not really okay. Also, the padding at the middle side of the page is too much such that the padding overshadows the entire page which is not supposed to be. I also think the fonts need to be adjusted especially for some individuals who uses glasses.  I can implement new fonts using Google fonts APIs. Do i have the permission to proceed and send a pull request. 

Also, are we to commit to the main branch or a separate branch.

**Comment by Nenepo** [comment]
I have fixed this issue

**Comment by iyinolawumi** [comment]
Hello @Nenepo I don’t think one person can work on an issue according to the guidelines we were given unless it has been pushed to the main branch and fixed. Has it? Also, since you have fixed it, it is still not showing here that it has been fixed. Do you have any comment on this . Thank you

**Comment by Nenepo** [comment]
@iyinolawumi  Okay my bad, I just wrote it because I worked on it and it was fixed, yes more than one person can work on an issue I’m sure, I have sent a pull request and it has not been merged yet as it was sent 20minutes ago and I don’t know when it would be merged. That is why you cannot see it fixed 
But if you check the pull request section you would see it

**Comment by iyinolawumi** [comment]
Ok. Thank you

**Comment by iyinolawumi** [comment]
I will also work on it again. I might notice something you might not see.

**Comment by Nenepo** [comment]
Definitely, go ahead

**Comment by egbadon-victor** [comment]
This actually occurs on screen sizes 680px and less

**Comment by OmarAmeen01** [comment]
linking this issue to the this issue https://github.com/creativecommons/vocabulary/issues/276 for a application of general fix to this problem
